In [1]:
import pandas as pd

In [2]:
import csv

In [3]:
T20matches_pd=pd.read_csv("t20_matches.csv")

In [4]:
T20matches_pd.head()

,match_id,series_id,match_details,result,scores,date,venue,round,home,away,...,innings1_wickets,innings1_overs_batted,innings1_overs,innings2,innings2_runs,innings2_wickets,innings2_overs_batted,innings2_overs,D/L_method,target
0,304744,124121,North Group:Durham v Nottinghamshire at Cheste...,Durham won by 6 wickets (with 5 balls remaining),Nottinghamshire 157/7 (20/20 ov); Durham 160/4...,13/06/2003,Chester-le-Street,North Group,Durham,Nottinghamshire,...,7.0,20.0,20.0,Durham,160.0,4.0,19.1,20.0,NaN,NaN
1,129610,124121,South Group:Hampshire v Sussex at Southampton-...,Hampshire won by 5 runs,Hampshire 153 (19.4/20 ov); Sussex 148/7 (20/2...,13/06/2003,Southampton,South Group,Hampshire,Sussex,...,10.0,19.4,20.0,Sussex,148.0,7.0,20.0,20.0,NaN,NaN
2,129597,124121,Midlands/Wales/West Group:Somerset v Warwicksh...,Warwickshire won by 19 runs,Warwickshire 188/7 (20/20 ov); Somerset 169 (2...,13/06/2003,Taunton,Midlands/Wales/West Group,Somerset,Warwickshire,...,7.0,20.0,20.0,Somerset,169.0,10.0,20.0,20.0,NaN,NaN
3,304745,124121,South Group:Surrey v Middlesex at The Oval- Ju...,Surrey won by 4 wickets (with 4 balls remaining),Middlesex 155 (20/20 ov); Surrey 158/6 (19.2/2...,13/06/2003,The Oval,South Group,Surrey,Middlesex,...,10.0,20.0,20.0,Surrey,158.0,6.0,19.2,20.0,NaN,NaN
4,304746,124121,Midlands/Wales/West Group:Worcestershire v Nor...,Worcestershire won by 1 wicket (with 2 balls r...,Northamptonshire 150/9 (20/20 ov); Worcestersh...,13/06/2003,Worcester,Midlands/Wales/West Group,Worcestershire,Northamptonshire,...,9.0,20.0,20.0,Worcestershire,151.0,9.0,19.4,20.0,NaN,NaN

## opening statement:
 ###

I have data set of the Match details of over 6000 T20 matches, including innings scores and results.I will try to perform the analysis through pandas and python on the role of pakistan cricket team with different angles.

In [ ]:
# I want firslty how many series are played in the data

In [19]:
T20matches_pd

,match_id,series_id,match_details,result,scores,date,venue,round,home,away,...,innings1_wickets,innings1_overs_batted,innings1_overs,innings2,innings2_runs,innings2_wickets,innings2_overs_batted,innings2_overs,D/L_method,target
0,304744,124121,North Group:Durham v Nottinghamshire at Cheste...,Durham won by 6 wickets (with 5 balls remaining),Nottinghamshire 157/7 (20/20 ov); Durham 160/4...,13/06/2003,Chester-le-Street,North Group,Durham,Nottinghamshire,...,7.0,20.0,20.0,Durham,160.0,4.0,19.1,20.0,NaN,NaN
1,129610,124121,South Group:Hampshire v Sussex at Southampton-...,Hampshire won by 5 runs,Hampshire 153 (19.4/20 ov); Sussex 148/7 (20/2...,13/06/2003,Southampton,South Group,Hampshire,Sussex,...,10.0,19.4,20.0,Sussex,148.0,7.0,20.0,20.0,NaN,NaN
2,129597,124121,Midlands/Wales/West Group:Somerset v Warwicksh...,Warwickshire won by 19 runs,Warwickshire 188/7 (20/20 ov); Somerset 169 (2...,13/06/2003,Taunton,Midlands/Wales/West Group,Somerset,Warwickshire,...,7.0,20.0,20.0,Somerset,169.0,10.0,20.0,20.0,NaN,NaN
3,304745,124121,South Group:Surrey v Middlesex at The Oval- Ju...,Surrey won by 4 wickets (with 4 balls remaining),Middlesex 155 (20/20 ov); Surrey 158/6 (19.2/2...,13/06/2003,The Oval,South Group,Surrey,Middlesex,...,10.0,20.0,20.0,Surrey,158.0,6.0,19.2,20.0,NaN,NaN
4,304746,124121,Midlands/Wales/West Group:Worcestershire v Nor...,Worcestershire won by 1 wicket (with 2 balls r...,Northamptonshire 150/9 (20/20 ov); Worcestersh...,13/06/2003,Worcester,Midlands/Wales/West Group,Worcestershire,Northamptonshire,...,9.0,20.0,20.0,Worcestershire,151.0,9.0,19.4,20.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,1083450,1083439,2nd T20I:Sri Lanka v Bangladesh at Colombo (RP...,Bangladesh won by 45 runs,Bangladesh 176/9 (20/20 ov); Sri Lanka 131 (18...,06/04/2017,Colombo (RPS),2nd T20I,Sri Lanka,Bangladesh,...,9.0,20.0,20.0,Sri Lanka,131.0,10.0,18.0,20.0,NaN,NaN
6413,1082591,1078425,1st match:Sunrisers Hyderabad v Royal Challeng...,Sunrisers Hyderabad won by 35 runs,Sunrisers Hyderabad 207/4 (20/20 ov); Royal Ch...,05/04/2017,Hyderabad (Deccan),1st match,Sunrisers Hyderabad,Royal Challengers Bangalore,...,4.0,20.0,20.0,Royal Challengers Bangalore,172.0,10.0,19.4,20.0,NaN,NaN
6414,1082592,1078425,2nd match:Rising Pune Supergiant v Mumbai Indi...,Rising Pune Supergiant won by 7 wickets (with ...,Mumbai Indians 184/8 (20/20 ov); Rising Pune S...,06/04/2017,Pune,2nd match,Rising Pune Supergiant,Mumbai Indians,...,8.0,20.0,20.0,Rising Pune Supergiant,187.0,3.0,19.5,20.0,NaN,NaN
6415,1082593,1078425,3rd match:Gujarat Lions v Kolkata Knight Rider...,Kolkata Knight Riders won by 10 wickets (with ...,Gujarat Lions 183/4 (20/20 ov); Kolkata Knight...,07/04/2017,Rajkot,3rd match,Gujarat Lions,Kolkata Knight Riders,...,4.0,20.0,20.0,Kolkata Knight Riders,184.0,0.0,14.5,20.0,NaN,NaN
6416,1082594,1078425,4th match:Kings XI Punjab v Rising Pune Superg...,Kings XI Punjab won by 6 wickets (with 6 balls...,Rising Pune Supergiant 163/6 (20/20 ov); Kings...,08/04/2017,Indore,4th match,Kings XI Punjab,Rising Pune Supergiant,...,6.0,20.0,20.0,Kings XI Punjab,164.0,4.0,19.0,20.0,NaN,NaN

In [11]:
T20matches_pd.series_id.value_counts()

series_id
435130    151
491208    151
691693    133
946653    133
803393    133
         ...
403364      1
255956      1
463138      1
521213      1
534188      1
Name: count, Length: 371, dtype: int64

In [5]:
with open("t20_matches.csv") as f:
    t20_matches=list(csv.reader(f))

In [6]:
header=t20_matches[0]
data=t20_matches[1:]

In [7]:
Serious_counts={}
for i in data:
    series=i[1]
    if series not in Serious_counts:
        Serious_counts[series] =1
    else:
        Serious_counts[series] +=1

In [8]:
len(Serious_counts)

371

In [ ]:
# 6417 matches has been played in 371 serious.

In [ ]:
# Another dataset has name of the series and winner of the series.

In [20]:
series_pd=pd.read_csv("t20_series.csv")

In [25]:
series_pd.loc[:,["series","winner"]]

                                                series       winner
0                                         Twenty20 Cup       Surrey
1         Standard Bank Pro20 Series (in South Africa)       Eagles
2                            Twenty20 Cup (in England)        Leics
3                  Twenty-20 Tournament (in Sri Lanka)       Chilaw
4                  Australia in New Zealand T20I Match    Australia
..                                                 ...          ...
368  Pakistan Super League (in Pakistan/United Arab...        Zalmi
369       Afghanistan v Ireland T20I Series (in India)  Afghanistan
370                Pakistan in West Indies T20I Series     Pakistan
371                Bangladesh in Sri Lanka T20I Series        drawn
372                   Indian Premier League (in India)            -

[373 rows x 2 columns]

In [30]:
series_pd["winner"]=="Pakistan"

0      False
1      False
2      False
3      False
4      False
       ...
368    False
369    False
370     True
371    False
372    False
Name: winner, Length: 373, dtype: bool

In [36]:
series_pd[series_pd["winner"]=="Pakistan"]

,series,season,winner,margin,series_id
22,Pakistan in England T20I Match,2006,Pakistan,1-0 (1),224904
49,Bangladesh in Pakistan T20I Match,2007/08,Pakistan,1-0 (1),343758
75,Australia v Pakistan T20I Match (in United Ara...,2009,Pakistan,1-0 (1),390287
79,ICC World Twenty20 (in England),2009,Pakistan,NaN,335113
83,Pakistan in Sri Lanka T20I Match,2009,Pakistan,1-0 (1),403364
88,Pakistan v New Zealand T20I Series (in United ...,2009/10,Pakistan,2-0 (2),426718
114,"MCC Spirit of Cricket T20I Series (Australia, ...",2010,Pakistan,2-0 (2),426347
143,Pakistan in Zimbabwe T20I Series,2011,Pakistan,2-0 (2),504009
154,Pakistan v Sri Lanka T20I Match (in United Ara...,2011/12,Pakistan,1-0 (1),530423
155,Pakistan in Bangladesh T20I Match,2011/12,Pakistan,1-0 (1),538065
188,Pakistan v Australia T20I Series (in United Ar...,2012,Pakistan,2-1 (3),571144
208,Pakistan in South Africa T20I Series,2012/13,Pakistan,1-0 (2),567347
227,Pakistan in West Indies T20I Series,2013,Pakistan,2-0 (2),645629
233,Pakistan in Zimbabwe T20I Series,2013,Pakistan,2-0 (2),659537
246,Afghanistan v Pakistan T20I Match (in United A...,2013/14,Pakistan,1-0 (1),698359
290,Zimbabwe in Pakistan T20I Series,2015,Pakistan,2-0 (2),868719
298,Pakistan in Sri Lanka T20I Series,2015,Pakistan,2-0 (2),860097
304,Pakistan in Zimbabwe T20I Series,2015/16,Pakistan,2-0 (2),904339
350,Pakistan in England T20I Match,2016,Pakistan,1-0 (1),913605
353,Pakistan v West Indies T20I Series (in United ...,2016/17,Pakistan,3-0 (3),1050201
370,Pakistan in West Indies T20I Series,2017,Pakistan,3-1 (4),1077945

In [ ]:
# I got the detail of the series won by the Pakistan.

In [ ]:
# now i want how many matches pakistan won and secondly how many pakistan won in home country.

In [48]:
(T20matches_pd["winner"] == "Pakistan") & (T20matches_pd["home"] == "Pakistan")

0       False
1       False
2       False
3       False
4       False
        ...
6412    False
6413    False
6414    False
6415    False
6416    False
Length: 6417, dtype: bool

In [40]:
T20matches_pd[T20matches_pd["winner"]=="Pakistan"]

,match_id,series_id,match_details,result,scores,date,venue,round,home,away,...,innings1_wickets,innings1_overs_batted,innings1_overs,innings2,innings2_runs,innings2_wickets,innings2_overs_batted,innings2_overs,D/L_method,target
480,225263,224904,Only T20I:England v Pakistan at Bristol- Aug 2...,Pakistan won by 5 wickets (with 13 balls remai...,England 144/7 (20/20 ov); Pakistan 148/5 (17.5...,28/08/2006,Bristol,Only T20I,England,Pakistan,...,7.0,20.0,20.0,Pakistan,148.0,5.0,17.5,20.0,NaN,NaN
750,306986,306979,1st Match:Pakistan v Uganda at Nairobi (Gym)- ...,Pakistan won by 148 runs,Pakistan 226/3 (20/20 ov); Uganda 78/7 (20/20 ov),01/09/2007,Nairobi (Gym),1st Match,Pakistan,Uganda,...,3.0,20.0,20.0,Uganda,78.0,7.0,20.0,20.0,NaN,NaN
753,306989,306979,4th Match:Bangladesh v Pakistan at Nairobi (Gy...,Pakistan won by 30 runs,Pakistan 191/7 (20/20 ov); Bangladesh 161/7 (2...,02/09/2007,Nairobi (Gym),4th Match,Bangladesh,Pakistan,...,7.0,20.0,20.0,Bangladesh,161.0,7.0,20.0,20.0,NaN,NaN
755,306991,306979,6th Match:Kenya v Pakistan at Nairobi (Gym)- S...,Pakistan won by 8 wickets (with 36 balls remai...,Kenya 92 (19.4/20 ov); Pakistan 93/2 (14/20 ov),04/09/2007,Nairobi (Gym),6th Match,Kenya,Pakistan,...,10.0,19.4,20.0,Pakistan,93.0,2.0,14.0,20.0,NaN,NaN
758,287855,286109,"3rd Match, Group D:Pakistan v Scotland at Durb...",Pakistan won by 51 runs,Pakistan 171/9 (20/20 ov); Scotland 120 (19.5/...,12/09/2007,Durban,"3rd Match, Group D",Pakistan,Scotland,...,9.0,20.0,20.0,Scotland,120.0,10.0,19.5,20.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6111,1050219,1050201,2nd T20I:Pakistan v West Indies at Dubai (DSC)...,Pakistan won by 16 runs,Pakistan 160/4 (20/20 ov); West Indies 144/9 (...,24/09/2016,Dubai (DSC),2nd T20I,Pakistan,West Indies,...,4.0,20.0,20.0,West Indies,144.0,9.0,20.0,20.0,NaN,NaN
6112,1050221,1050201,3rd T20I:Pakistan v West Indies at Abu Dhabi- ...,Pakistan won by 8 wickets (with 29 balls remai...,West Indies 103/5 (20/20 ov); Pakistan 108/2 (...,27/09/2016,Abu Dhabi,3rd T20I,Pakistan,West Indies,...,5.0,20.0,20.0,Pakistan,108.0,2.0,15.1,20.0,NaN,NaN
6407,1077947,1077945,1st T20I:West Indies v Pakistan at Bridgetown-...,Pakistan won by 6 wickets (with 17 balls remai...,West Indies 111/8 (20/20 ov); Pakistan 115/4 (...,26/03/2017,Bridgetown,1st T20I,West Indies,Pakistan,...,8.0,20.0,20.0,Pakistan,115.0,4.0,17.1,20.0,NaN,NaN
6408,1077948,1077945,2nd T20I:West Indies v Pakistan at Port of Spa...,Pakistan won by 3 runs,Pakistan 132 (20/20 ov); West Indies 129/8 (20...,30/03/2017,Port of Spain,2nd T20I,West Indies,Pakistan,...,10.0,20.0,20.0,West Indies,129.0,8.0,20.0,20.0,NaN,NaN
6410,1085496,1077945,4th T20I:West Indies v Pakistan at Port of Sp...,Pakistan won by 7 wickets (with 6 balls remain...,West Indies 124/8 (20/20 ov); Pakistan 127/3 (...,02/04/2017,Port of Spain,4th T20I,West Indies,Pakistan,...,8.0,20.0,20.0,Pakistan,127.0,3.0,19.0,20.0,NaN,NaN

In [49]:
T20matches_pd[(T20matches_pd["winner"] == "Pakistan") & (T20matches_pd["home"] == "Pakistan")]

,match_id,series_id,match_details,result,scores,date,venue,round,home,away,...,innings1_wickets,innings1_overs_batted,innings1_overs,innings2,innings2_runs,innings2_wickets,innings2_overs_batted,innings2_overs,D/L_method,target
750,306986,306979,1st Match:Pakistan v Uganda at Nairobi (Gym)- ...,Pakistan won by 148 runs,Pakistan 226/3 (20/20 ov); Uganda 78/7 (20/20 ov),01/09/2007,Nairobi (Gym),1st Match,Pakistan,Uganda,...,3.0,20.0,20.0,Uganda,78.0,7.0,20.0,20.0,NaN,NaN
758,287855,286109,"3rd Match, Group D:Pakistan v Scotland at Durb...",Pakistan won by 51 runs,Pakistan 171/9 (20/20 ov); Scotland 120 (19.5/...,12/09/2007,Durban,"3rd Match, Group D",Pakistan,Scotland,...,9.0,20.0,20.0,Scotland,120.0,10.0,19.5,20.0,NaN,NaN
771,287868,286109,"16th Match, Group F:Pakistan v Sri Lanka at Jo...",Pakistan won by 33 runs,Pakistan 189/6 (20/20 ov); Sri Lanka 156/9 (20...,17/09/2007,Johannesburg,"16th Match, Group F",Pakistan,Sri Lanka,...,6.0,20.0,20.0,Sri Lanka,156.0,9.0,20.0,20.0,NaN,NaN
854,343764,343758,Only T20I:Pakistan v Bangladesh at Karachi- Ap...,Pakistan won by 102 runs,Pakistan 203/5 (20/20 ov); Bangladesh 101 (16/...,20/04/2008,Karachi,Only T20I,Pakistan,Bangladesh,...,5.0,20.0,20.0,Bangladesh,101.0,10.0,16.0,20.0,NaN,NaN
1089,361656,361644,4th Match:Pakistan v Sri Lanka at King City (N...,Pakistan won by 3 wickets (with 1 ball remaining),Sri Lanka 137/9 (20/20 ov); Pakistan 141/7 (19...,11/10/2008,King City (NW),4th Match,Pakistan,Sri Lanka,...,9.0,20.0,20.0,Pakistan,141.0,7.0,19.5,20.0,NaN,NaN
1090,361657,361644,5th Match:Pakistan v Zimbabwe at King City (NW...,Pakistan won by 7 wickets (with 6 balls remain...,Zimbabwe 107/8 (20/20 ov); Pakistan 110/3 (19/...,12/10/2008,King City (NW),5th Match,Pakistan,Zimbabwe,...,8.0,20.0,20.0,Pakistan,110.0,3.0,19.0,20.0,NaN,NaN
1312,356015,335113,1st Semi-Final:Pakistan v South Africa at Nott...,Pakistan won by 7 runs,Pakistan 149/4 (20/20 ov); South Africa 142/5 ...,18/06/2009,Nottingham,1st Semi-Final,Pakistan,South Africa,...,4.0,20.0,20.0,South Africa,142.0,5.0,20.0,20.0,NaN,NaN
1314,356017,335113,"Final:Pakistan v Sri Lanka at Lord's- Jun 21, ...",Pakistan won by 8 wickets (with 8 balls remain...,Sri Lanka 138/6 (20/20 ov); Pakistan 139/2 (18...,21/06/2009,Lord's,Final,Pakistan,Sri Lanka,...,6.0,20.0,20.0,Pakistan,139.0,2.0,18.4,20.0,NaN,NaN
1775,412697,412671,"21st Match, Group E:Pakistan v South Africa at...",Pakistan won by 11 runs,Pakistan 148/7 (20/20 ov); South Africa 137/7 ...,10/05/2010,Gros Islet,"21st Match, Group E",Pakistan,South Africa,...,7.0,20.0,20.0,South Africa,137.0,7.0,20.0,20.0,NaN,NaN
2534,530432,530423,Only T20I:Pakistan v Sri Lanka at Abu Dhabi- N...,Pakistan won by 5 wickets (with 3 balls remain...,Sri Lanka 141 (19.3/20 ov); Pakistan 142/5 (19...,25/11/2011,Abu Dhabi,Only T20I,Pakistan,Sri Lanka,...,10.0,19.3,20.0,Pakistan,142.0,5.0,19.3,20.0,NaN,NaN
3220,533286,531597,"15th Match, Group 2:Pakistan v South Africa at...",Pakistan won by 2 wickets (with 2 balls remain...,South Africa 133/6 (20/20 ov); Pakistan 136/8 ...,28/09/2012,Colombo (RPS),"15th Match, Group 2",Pakistan,South Africa,...,6.0,20.0,20.0,Pakistan,136.0,8.0,19.4,20.0,NaN,NaN
4079,657633,657621,1st T20I:Pakistan v Sri Lanka at Dubai (DSC)- ...,Pakistan won by 3 wickets (with 5 balls remain...,Sri Lanka 145/5 (20/20 ov); Pakistan 146/7 (19...,11/12/2013,Dubai (DSC),1st T20I,Pakistan,Sri Lanka,...,5.0,20.0,20.0,Pakistan,146.0,7.0,19.1,20.0,NaN,NaN
5069,868723,868719,1st T20I:Pakistan v Zimbabwe at Lahore- May 22...,Pakistan won by 5 wickets (with 3 balls remain...,Zimbabwe 172/6 (20/20 ov); Pakistan 173/5 (19....,22/05/2015,Lahore,1st T20I,Pakistan,Zimbabwe,...,6.0,20.0,20.0,Pakistan,173.0,5.0,19.3,20.0,NaN,NaN
5070,868725,868719,2nd T20I:Pakistan v Zimbabwe at Lahore- May 24...,Pakistan won by 2 wickets (with 2 balls remain...,Zimbabwe 175/3 (20/20 ov); Pakistan 176/8 (19....,24/05/2015,Lahore,2nd T20I,Pakistan,Zimbabwe,...,3.0,20.0,20.0,Pakistan,176.0,8.0,19.4,20.0,NaN,NaN
5769,966755,966595,6th Match:Pakistan v United Arab Emirates at D...,Pakistan won by 7 wickets (with 8 balls remain...,United Arab Emirates 129/6 (20/20 ov); Pakista...,29/02/2016,Dhaka,6th Match,Pakistan,United Arab Emirates,...,6.0,20.0,20.0,Pakistan,131.0,3.0,18.4,20.0,NaN,NaN
5773,966763,966595,10th Match:Pakistan v Sri Lanka at Dhaka- Mar ...,Pakistan won by 6 wickets (with 4 balls remain...,Sri Lanka 150/4 (20/20 ov); Pakistan 151/4 (19...,04/03/2016,Dhaka,10th Match,Pakistan,Sri Lanka,...,4.0,20.0,20.0,Pakistan,151.0,4.0,19.2,20.0,NaN,NaN
6110,1050217,1050201,1st T20I:Pakistan v West Indies at Dubai (DSC)...,Pakistan won by 9 wickets (with 34 balls remai...,West Indies 115 (19.5/20 ov); Pakistan 116/1 (...,23/09/2016,Dubai (DSC),1st T20I,Pakistan,West Indies,...,10.0,19.5,20.0,Pakistan,116.0,1.0,14.2,20.0,NaN,NaN
6111,1050219,1050201,2nd T20I:Pakistan v West Indies at Dubai (DSC)...,Pakistan won by 16 runs,Pakistan 160/4 (20/20 ov); West Indies 144/9 (...,24/09/2016,Dubai (DSC),2nd T20I,Pakistan,West Indies,...,4.0,20.0,20.0,West Indies,144.0,9.0,20.0,20.0,NaN,NaN
6112,1050221,1050201,3rd T20I:Pakistan v West Indies at Abu Dhabi- ...,Pakistan won by 8 wickets (with 29 balls remai...,West Indies 103/5 (20/20 ov); Pakistan 108/2 (...,27/09/2016,Abu Dhabi,3rd T20I,Pakistan,West Indies,...,5.0,20.0,20.0,Pakistan,108.0,2.0,15.1,20.0,NaN,NaN

In [ ]:
##out of 69 matches pakistan won 19 matches in the home country.

In [ ]:
I want the score column when pakistan played the matches

In [17]:
((T20matches_pd["home"]=="Pakistan") | (T20matches_pd["away"]=="Pakistan")).sum()

116

In [19]:
(T20matches_pd["home"]=="Pakistan").sum()

27

In [ ]:
# pakistan played 116 matches in different series and won 69 matches and out of which it won 27 matches in home country 
#and won 19 matches. Now i want the total score card of the matches pakistan played.

In [20]:
T20matches_pd.loc[(T20matches_pd["home"]=="Pakistan") | (T20matches_pd["away"]=="Pakistan")]["scores"]

480     England 144/7 (20/20 ov); Pakistan 148/5 (17.5...
526     Pakistan 129/8 (20/20 ov); South Africa 132/0 ...
750     Pakistan 226/3 (20/20 ov); Uganda 78/7 (20/20 ov)
753     Pakistan 191/7 (20/20 ov); Bangladesh 161/7 (2...
755       Kenya 92 (19.4/20 ov); Pakistan 93/2 (14/20 ov)
                              ...
6112    West Indies 103/5 (20/20 ov); Pakistan 108/2 (...
6407    West Indies 111/8 (20/20 ov); Pakistan 115/4 (...
6408    Pakistan 132 (20/20 ov); West Indies 129/8 (20...
6409    Pakistan 137/8 (20/20 ov); West Indies 138/3 (...
6410    West Indies 124/8 (20/20 ov); Pakistan 127/3 (...
Name: scores, Length: 116, dtype: object

In [30]:
T20matches_pd["innings1"].value_counts().sort_values(ascending=False).head(60)

innings1
Surrey                         98
Chennai Super Kings            91
Mumbai Indians                 90
Leicestershire                 89
Hampshire                      88
Lancashire                     84
Kent                           80
Northamptonshire               80
Somerset                       79
Yorkshire                      75
Nottinghamshire                74
Derbyshire                     71
Sussex                         70
Kings XI Punjab                70
Middlesex                      69
Warwickshire                   69
Royal Challengers Bangalore    69
Worcestershire                 68
Kolkata Knight Riders          68
Essex                          66
Glamorgan                      66
Cape Cobras                    65
Durham                         65
Delhi Daredevils               62
Gloucestershire                62
Dolphins                       60
Pakistan                       59
Northern Districts             58
Titans                         58
Lions                          58
Auckland                       57
Rajasthan Royals               57
Warriors                       55
South Africa                   54
Otago                          52
New Zealand                    49
Central Districts              49
Canterbury                     48
Sri Lanka                      48
England                        47
Namibia                        47
Australia                      45
West Indies                    45
Deccan Chargers                44
Wellington                     42
Lahore Lions                   42
Kenya                          41
Afghanistan                    41
Perth Scorchers                41
Sunrisers Hyderabad            40
India                          40
Ireland                        38
Bengal                         36
Faisalabad Wolves              36
Haryana                        34
Knights                        33
Canada                         32
Zimbabwe                       32
Punjab                         32
Bangladesh                     32
Name: count, dtype: int64

# pakistan palyed 59 matches as first inings out of 116 and 56 as second inning

In [31]:
T20matches_pd["innings2"].value_counts().sort_values(ascending=False).head(60)

innings2
Somerset                       87
Royal Challengers Bangalore    86
Essex                          86
Sussex                         83
Warwickshire                   82
Middlesex                      81
Kolkata Knight Riders          80
Gloucestershire                79
Delhi Daredevils               78
Kent                           74
Yorkshire                      73
Durham                         73
Mumbai Indians                 73
Hampshire                      73
Nottinghamshire                71
Glamorgan                      71
Kings XI Punjab                70
Lancashire                     69
Northamptonshire               69
Worcestershire                 69
Rajasthan Royals               67
Titans                         65
Derbyshire                     65
Lions                          64
Chennai Super Kings            64
Warriors                       63
Leicestershire                 61
Surrey                         57
Auckland                       57
Pakistan                       56
Wellington                     55
Cape Cobras                    53
Northern Districts             52
Central Districts              50
Canterbury                     49
Dolphins                       49
England                        48
Otago                          48
Australia                      48
Sri Lanka                      47
New Zealand                    46
India                          40
South Africa                   40
Afghanistan                    40
Bangladesh                     39
Sialkot Stallions              39
Ireland                        39
West Indies                    39
Netherlands                    38
Sydney Sixers                  36
Scotland                       34
Punjab                         33
Delhi                          33
Knights                        33
Deccan Chargers                33
Madhya Pradesh                 32
Faisalabad Wolves              32
Karachi Dolphins               32
Melbourne Stars                31
Kenya                          31
Name: count, dtype: int64

In [38]:
((T20matches_pd["innings1"] == "") & ((T20matches_pd["home"] == "Pakistan") | (T20matches_pd["away"] == "Pakistan"))).sum()

0

In [40]:
T20matches_pd[(T20matches_pd["result"] == "Match abandoned without a ball bowled") & ((T20matches_pd["home"] == "Pakistan") | (T20matches_pd["away"] == "Pakistan"))]

,match_id,series_id,match_details,result,scores,date,venue,round,home,away,...,innings1_wickets,innings1_overs_batted,innings1_overs,innings2,innings2_runs,innings2_wickets,innings2_overs_batted,innings2_overs,D/L_method,target
3481,567366,567347,1st T20I:South Africa v Pakistan at Durban- Ma...,Match abandoned without a ball bowled,NaN,01/03/2013,Durban,1st T20I,South Africa,Pakistan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Now we reach to point that pakistan played 116 matches out of 115 matches were valid and one match were cancelled due to rain

In [42]:
pakistani_matches=T20matches_pd[(T20matches_pd["home"]=="Pakistan") | (T20matches_pd["away"]=="Pakistan")]

In [44]:
((pakistani_matches["home"]!="Pakistan")  | (pakistani_matches["away"]!="Pakistan")).

116